### ISSUE TITLE
Remove Deprecated Objects

### ISSUE THREAD

**Issue by Christo6** [FRC1726/NERDS_Competition_2018#3]
A few different pieces of code have been deprecated in the 2018 WPI Libraries. These include:
RobotDrive, which has been replaced (in our use case) by DifferentialDrive
LiveWindows::GetInstance::Run() is no longer needed in TestPeriodic

**Comment by Bakushawn** [comment]
I fixed it by updating outdated classes, remapped the controller axis to correct pins
