### ISSUE TITLE
Winch Solenoid prematurely activates during autonomous 

### ISSUE THREAD

**Issue by Bakushawn** [FRC1726/NERDS_Competition_2018#56]
The solenoid for the winch trigger, it switches states when enabled, and despite a partial fix solving it, whenever we turn the robot off, turn it on, and enable the solenoid switches states. So we can fix it in the pits, but then we need to turn the robot off to load it onto the field, and then when running it on the field, enabling switches the solenoid

**Comment by dtanguay** [comment]
I wish I was more conversant in C++ but I can kind of follow the logical flow of events. My assessment of the problem concerns the file ReleaseWinch.cpp. In the snippet below:

// Called just before this Command runs the first time
void ReleaseWinch::Initialize() {
*/ want to set to false, not toggled. We need to start in a known state after the robot is turned on. */
	winch.setRelease(!winch.getRelease());         // don't want to toggle the release******
}

// Called repeatedly when this Command is scheduled to run
void ReleaseWinch::Execute() {
*/***** I'm guessing this is where the code should look at the appropriate button of the game controller
         and set the release to true when pressed. Set release to false if button is no longer pressed. ***/
} 


Hope this helps.

**Comment by Christo6** [comment]
We can set it to stay on when a button is pressed, but I doubt that will fix the problem. All commands that are bound to buttons are in the oi.cpp file.

We set the initial state of the solenoid in the winch subsystem. Not sure why it toggles during autonomous though. Does it also toggle when you start in teleop?

**Comment by Christo6** [comment]
Actually, I think I know what it is. When the mechanical team hooked the pneumatics back up last time they did it in reverse of what it had been before. We switched it in our test code, but never made the change to the master branch.

The value given to the release solenoid in winch's constructor needs to be reversed. Or mechanical needs to stop reversing wires and tubes on the robot.

**Comment by dtanguay** [comment]
It does it in teleop also.

**Comment by dtanguay** [comment]
Oh and I did see the winchRelease code in OI.cpp . Now I see how that works
and that should not be a problem in actual operation. We just need to be
sure to initialize the release to a known state upon robot startup. The
mechanical people will just have to ensure the plumbing matches the code.

**Comment by dtanguay** [comment]
// Process operator interface input here.
	driver_a.WhenPressed(new ToggleClaw);
	driver_x.WhenPressed(new WristUp);
	driver_y.WhenPressed(new WristDown);
	driver_b.WhenPressed(new ToggleElevator);
	driver_RB.WhenPressed(new ReleaseWinch); // Would WhilePressed be more appropriate here?
	driver_LB.WhenPressed(new InitClaw);

	d_Down.WhileActive(new ReelDown);
	d_Up.WhileActive(new ReelUp);
}

**Comment by Christo6** [comment]
No. We want it to toggle once when the button is pressed. The piston should stay retracted until the button is pressed again so that the driver doesn't have to hold down the button while reeling the winch. 

The place you are looking for to initialize the the value is in the constructor for the Winch subsystem. Here is the code currently:

`Winch::Winch() : Subsystem("Winch"),
	release(WINCH_RELEASE),
	reel(WINCH_REEL)
{
	release.Set(true);
}`

You just need to change the true to false and it should be good.

**Comment by dtanguay** [comment]
Concur.
