### ISSUE TITLE
Joystick Driving Not Interuptted

### ISSUE THREAD

**Issue by Coronado16** [FRC1726/NERDS_Competition_2018#7]
The ArcadeDriveWithJoysticks program does not seem to get interrupted. This prevents other drivetrain commands from running.

**Comment by DipperPines1** [comment]
Ok

**Comment by Christo6** [comment]
The pointer to the drivetrain system was not initializing before the Requires for the commands were called. Fixed it by changing the drivetrain to an object rather than a pointer.
